=== NikCharlebois/DSCStudio/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "metadata": {
            "type": "object",
            "description": "Metadata to describe this template",
            "properties": {
                "title": {
                    "type": "string",
                    "description": "The display name of the template"
                },
                "configurationName": {
                    "type": "string",
                    "description": "The name of the configuration that will be generated with this template"
                },
                "description": {
                    "type": "string",
                    "description": "A description of the template"
                }
            },
            "required": [
                "title",
                "configurationName"
            ]
        },
        "dscModules": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the DSC module as it appears on the PowerShell gallery"
                    },
                    "version": {
                        "type": "string",
                        "description": "The version number of the module that is used for this template"
                    }
                },
                "required": [
                    "name"
                ]
            }
        },
        "configDataSettings": {
            "type": "object",
            "properties": {
                "nodeSettings": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "powershellName": {
                                "type": "string",
                                "description": "The name of this property to be used in PowerShell scripts"
                            },
                            "displayName": {
                                "type": "string",
                                "description": "The name of the property as shown in the DSC Studio UI"
                            },
                            "valueType": {
                                "type": "string",
                                "description": "The type of this property to ask the user for",
                                "enum": [
                                    "text",
                                    "number",
                                    "boolean"
                                ]
                            },
                            "minOccurences": {
                                "type": "integer",
                                "description": "For boolean properties - the minimum number of nodes that must have this set to 'true' for a configuration to be valid"
                            },
                            "maxOccurences": {
                                "type": "integer",
                                "description": "For boolean properties - the maximum number of nodes that can have this set to 'true' for a configuration to be valid"
                            }
                        },
                        "required": [
                            "powershellName",
                            "displayName",
                            "valueType"
                        ]
                    }
                },
                "certificateDetails": {
                    "type": "boolean",
                    "description": "Ask for a certificate thumbprint and path to CER file to allow for encryption of credentials, setting to false will configure DSC to allow plain text passwords (NOT RECOMMENDED)",
                    "default": true
                },
                "allowPlainTextPassword": {
                    "type": "boolean",
                    "description": "Not recommended - Should this template allow users to use plain text passwords in the output? Default is false",
                    "default": false
                },
                "minNodeCount": {
                    "type": "integer",
                    "description": "The minimum number of nodes to be added to this configuration (defaults to 1 if not specified)",
                    "default": 1
                },
                "maxNodeCount": {
                    "type": "integer",
                    "description": "The maximum numbder of nodes that can be added to this configuration (no limit if not specified)"
                }
            }
        },
        "questions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string",
                        "description": "An internal ID for this question to use when refering to it in resource values"
                    },
                    "title": {
                        "type": "string",
                        "description": "The name of the question to show to the user"
                    },
                    "type": {
                        "type": "string",
                        "description": "The type of question to show to the user",
                        "enum": [
                            "text",
                            "number",
                            "boolean",
                            "filepath",
                            "regex",
                            "choice"
                        ]
                    },
                    "defaultValue": {
                        "type": "string",
                        "description": "What should the default value of this question be?"
                    },
                    "group": {
                        "type": "string",
                        "description": "A group heading to put this question in to"
                    },
                    "helpText": {
                        "type": "string",
                        "description": "Additional help text that can be shown for a specific question."
                    },
                    "validationMessage": {
                        "type": "string",
                        "description": "The validation error message to be shown to the user"
                    },
                    "minValue": {
                        "type": "integer",
                        "description": "The minimum value of this field (for number fields only)"
                    },
                    "maxValue": {
                        "type": "integer",
                        "description": "The minimum value of this field (for number fields only)"
                    },
                    "pattern": {
                        "type": "string",
                        "description": "The regular expression to validate this field with (for regex fields only)"
                    },
                    "choices": {
                        "type": "array",
                        "description": "A list of choices to present the user for this question type",
                        "items": {
                            "type": "string"
                        }
                    },
                    "showForTrueResponseQuestion": {
                        "type": "string",
                        "description": "The ID of a boolean question that controls whether or not this question should be displayed and validated"
                    }
                },
                "required": [
                    "id",
                    "title",
                    "type"
                ]
            }
        },
        "inputParameters": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "The name of the parameter to add to the configuration"
                    },
                    "parameterType": {
                        "type": "string",
                        "description": "The object type in PowerShell for this parameter"
                    }
                },
                "required": [
                    "name",
                    "parameterType"
                ]
            }
        },
        "outputResources": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "resourceType": {
                        "type": "string",
                        "description": "The name of the DSC resource to include"
                    },
                    "resourceName": {
                        "type": "string",
                        "description": "The friendly name to put on to this resource"
                    },
                    "resourceProperties": {
                        "type": "object",
                        "description": "A list of the properties and values to include on this resource"
                    },
                    "dependsOn": {
                        "type": "string",
                        "description": "The DependsOn value for this resource"
                    },
                    "includeQuestion": {
                        "type": "string",
                        "description": "The ID of a boolean question that determines if this resource should be included or not"
                    },
                    "includeNodeDataProperty": {
                        "type": "string",
                        "description": "The powershell name of a node data question that determines if this resource should be included or not"
                    },
                    "includeScriptTest": {
                        "type": "string",
                        "description": "A PowerShell statement that should evaluate to $true or $false to determine if this resource applies to the current node"
                    }
                },
                "required": [
                    "resourceType",
                    "resourceName",
                    "resourceProperties"
                ]
            }    
        }
    }
}

=== NikCharlebois/DSCStudio/modules/DscStudioExampleTemplates/DSCTemplates/SharePoint2016-SingleServer.json
{
    "$schema": "./schema.json",
    "metadata": {
        "title": "SharePoint Server 2016 (Single Server)",
        "description": "Used to create a SharePoint Server 2016 deployment on a single server",
        "configurationName": "SharePointSingleServer"
    },
    "dscModules": [
        {
            "name": "SharePointDsc",
            "version": "1.4.0.0"
        }
    ],
    "questions": [
        {
            "id": "BINARYPATH",
            "title": "Where are the SharePoint installation files stored on the local server?",
            "type": "filepath",
            "group": "Installation",
            "validationMessage": "This must be a valid file path"
        },
        {
            "id": "PRODUCTKEY",
            "title": "What is your SharePoint 2016 product key?",
            "type": "regex",
            "group": "Farm configuration",
            "pattern": "/^[A-Za-z0-9]{5}-[A-Za-z0-9]{5}-[A-Za-z0-9]{5}-[A-Za-z0-9]{5}-[A-Za-z0-9]{5}/g",
            "validationMessage": "Must be a valid product key, formatted as XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"
        },
        {
            "id": "SQLSERVERNAME",
            "title": "What is the name of the SQL server that will host your databases?",
            "type": "text",
            "group": "Database details"
        },
        {
            "id": "LOGPATH",
            "title": "Where should ULS and usage logs be stored?",
            "type": "filepath",
            "group": "Logging",
            "validationMessage": "This must be a valid file path"
        },
        {
            "id": "LOGSIZE",
            "title": "Size (in GB) to allow for storing ULS logs",
            "type": "number",
            "group": "Logging",
            "minValue": 1,
            "validationMessage": "This field must be a valid number above 0"
        },
        {
            "id": "CACHESIZE",
            "title": "How many MB of memory should be allocated to the distributed cache service?",
            "type": "number",
            "group": "Farm configuration",
            "helpText": "Distributed cache needs to have a maximum amount of memory set on the the servers running this role. The maximum support is 16384 (16GB) however the amount you select will vary based on available memory and workloads on each server.",
            "minValue": 1,
            "maxValue": 16384,
            "validationMessage": "This field must be a valid number between 1 and 16384"
        },
        {
            "id": "WEBAPPDOMAIN",
            "title": "What will the domain name be that hosts SharePoint sites? (eg. sharepoint.contoso.com)",
            "type": "text",
            "group": "Web application details",
            "helpText": "The domain name that will be used for the main web application (note: do not include the 'http://' at the start, just use the domain name)"
        },
        {
            "id": "SUPERUSER",
            "title": "The username of the super user account (formatted as DOMAIN\\USER)",
            "type": "text",
            "group": "Web application details"
        },
        {
            "id": "SUPERREADER",
            "title": "The username of the super reader account (formatted as DOMAIN\\USER)",
            "type": "text",
            "group": "Web application details"
        },
        {
            "id": "PROVISION-MMS",
            "title": "Deploy the managed metadata service app to this farm?",
            "type": "boolean",
            "group": "Service applications"
        },
        {
            "id": "PROVISION-SECURESTORE",
            "title": "Deploy the secure store service app to this farm?",
            "type": "boolean",
            "group": "Service applications"
        },
        {
            "id": "PROVISION-BCS",
            "title": "Deploy the BCS service app to this farm?",
            "type": "boolean",
            "group": "Service applications"
        },
        {
            "id": "INDEXPATH",
            "title": "Where should search index partitions be stored?",
            "type": "filepath",
            "validationMessage": "This must be a valid directory (do not include the '\\' on the end)",
            "group": "Search"
        }
    ],
    "configDataSettings": {
        "certificateDetails": true,
        "nodeSettings": [],
        "maxNodeCount": 1
    },
    "inputParameters": [
        {
            "name": "FarmAccount",
            "parameterType": "PSCredential"
        },
        {
            "name": "SetupAccount",
            "parameterType": "PSCredential"
        },
        {
            "name": "WebPoolManagedAccount",
            "parameterType": "PSCredential"
        },
        {
            "name": "ServicePoolManagedAccount",
            "parameterType": "PSCredential"
        },
        {
            "name": "Passphrase",
            "parameterType": "PSCredential"
        }
    ],
    "outputResources": [
        {
            "resourceType": "SPInstallPrereqs",
            "resourceName": "InstallPrereqs",
            "resourceProperties": {
                "Ensure": "Present",
                "InstallerPath": "[BINARYPATH]\\prerequisiteinstaller.exe",
                "OnlineMode": "$true"
            }
        },
        {
            "resourceType": "SPInstall",
            "resourceName": "InstallSharePoint",
            "resourceProperties": {
                "Ensure": "Present",
                "BinaryDir": "[BINARYPATH]",
                "ProductKey": "[PRODUCTKEY]"
            },
            "dependsOn": "[SPInstallPrereqs]InstallPrereqs"
        },
        {
            "resourceType": "SPCreateFarm",
            "resourceName": "CreateNewFarm",
            "resourceProperties": {
                "DatabaseServer": "[SQLSERVERNAME]",
                "FarmConfigDatabaseName": "SP_Config",
                "AdminContentDatabaseName": "SP_AdminContent",
                "Passphrase": "$Passphrase",
                "FarmAccount": "$FarmAccount",
                "PsDscRunAsCredential": "$SetupAccount"
            },
            "dependsOn": "[SPInstall]InstallSharePoint"
        },
        {
            "resourceType": "SPManagedAccount",
            "resourceName": "ServicePoolManagedAccount",
            "resourceProperties": {
                "AccountName": "$ServicePoolManagedAccount.UserName",
                "Account": "$ServicePoolManagedAccount",
                "PsDscRunAsCredential": "$SPSetupAccount"
            },
            "dependsOn": "[SPCreateFarm]CreateSPFarm"
        },
        {
            "resourceType": "SPManagedAccount",
            "resourceName": "WebPoolManagedAccount",
            "resourceProperties": {
                "AccountName": "$WebPoolManagedAccount.UserName",
                "Account": "$WebPoolManagedAccount",
                "PsDscRunAsCredential": "$SPSetupAccount"
            },
            "dependsOn": "[SPCreateFarm]CreateSPFarm"
        },
        {
            "resourceType": "SPDiagnosticLoggingSettings",
            "resourceName": "ApplyDiagnosticLogSettings",
            "resourceProperties": {
                "PsDscRunAsCredential": "$SPSetupAccount",
                "LogSpaceInGB": "[LOGSIZE]",
                "LogPath": "[LOGPATH]"
            },
            "dependsOn": "[SPCreateFarm]CreateSPFarm"
        },
        {
            "resourceType": "SPUsageApplication",
            "resourceName": "UsageApplication",
            "resourceProperties": {
                "Name": "Usage Service Application",
                "DatabaseName": "SP_Usage",
                "UsageLogLocation": "[LOGPATH]",
                "PsDscRunAsCredential": "$SPSetupAccount"
            },
            "dependsOn": "[SPCreateFarm]CreateSPFarm"
        },
        {
            "resourceType": "SPStateServiceApp",
            "resourceName": "StateServiceApp",
            "resourceProperties": {
                "Name": "State Service Application",
                "DatabaseName": "SP_State",
                "PsDscRunAsCredential": "$SPSetupAccount"
            },
            "dependsOn": "[SPCreateFarm]CreateSPFarm"
        },
        {
            "resourceType": "SPDistributedCacheService",
            "resourceName": "EnableDistributedCache",
            "resourceProperties": {
                "Name": "AppFabricCachingService",
                "Ensure": "Present",
                "CacheSizeInMB": "[CACHESIZE]",
                "ServiceAccount": "$ServicePoolManagedAccount.UserName",
                "CreateFirewallRules": "$true",
                "PsDscRunAsCredential": "$SPSetupAccount"
            },
            "dependsOn": "[SPCreateFarm]CreateSPFarm"
        },
        {
            "resourceType": "SPWebApplication",
            "resourceName": "SharePointSites",
            "resourceProperties": {
                "Name": "SharePoint Sites",
                "ApplicationPool": "SharePoint Sites",
                "ApplicationPoolAccount": "$WebPoolManagedAccount.UserName",
                "DatabaseName": "SP_Content",
                "Url": "http://[WEBAPPDOMAIN]",
                "HostHeader": "[WEBAPPDOMAIN]",
                "Port": "80",
                "PsDscRunAsCredential": "$SPSetupAccount"
            },
            "dependsOn": "[SPManagedAccount]WebPoolManagedAccount"
        },
        {
            "resourceType": "SPCacheAccounts",
            "resourceName": "WebAppCacheAccounts",
            "resourceProperties": {
                "WebAppUrl": "http://[WEBAPPDOMAIN]",
                "SuperUserAlias": "[SUPERUSER]",
                "SuperReaderAlias": "[SUPERREADER]",
                "PsDscRunAsCredential": "$SPSetupAccount"
            },
            "dependsOn": "[SPWebApplication]SharePointSites"
        },
        {
            "resourceType": "SPSite",
            "resourceName": "TeamSite",
            "resourceProperties": {
                "Url": "http://[WEBAPPDOMAIN]",
                "OwnerAlias": "$FarmAccount",
